[dependencies]
pinocchio.workspace = true

[dev-dependencies]
mollusk-svm.workspace = true
test-utils.path = "../utils/test-utils"

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[package]
edition = "2021"
name = "hello-dasmac"
version = "0.1.0"
