[workspace]
resolver = "2"
members = ["hello-dasmac"]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }

[workspace.dependencies]
mollusk-svm = "0.4.1"
pinocchio = "0.9.2"
solana-sdk = "2.2.1"