[workspace]
resolver = "2"
members = ["hello-dasmac"]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }

[workspace.dependencies]
mollusk-svm = "0.7.2"
pinocchio = "0.9.2"
solana-sbpf = "0.13.0"
solana-sdk = "3.0.0"

[workspace.metadata.solana]
tools-version = "v1.51"