[dependencies]
pinocchio.workspace = true

[dev-dependencies]
test-utils = {path = "../test-utils"}
mollusk-svm.workspace = true
solana-sdk.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[package]
edition = "2021"
name = "memo"
version = "0.1.0"
